### ISSUE TITLE
[12.0] [FIX] Tax Rounding in stock_picking_report_valued

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/stock-logistics-reporting#115]
To replicate this issue:

1 - Set the Round globally option (Invoicing settings) and allow discounts (sale settings)

2- Create the next quotation
![image](https://user-images.githubusercontent.com/24428859/93372216-de134400-f853-11ea-9ce5-4b160baccb04.png)

3 - Confirm the quotation and check the differences in the quotation, invoice and the Delivery Slip report
![image](https://user-images.githubusercontent.com/24428859/93372434-2fbbce80-f854-11ea-906f-27c6ec04ab24.png)

**Comment by pedrobaeza** [comment]
Odoo version? What is the tax total in invoices?

**Comment by emagdalenaC2i** [comment]
I think this affect all versions but I check it with 12.0
Invoices taxes and total are the same as in the quotation

**Comment by emagdalenaC2i** [comment]
This is the invoice 
![image](https://user-images.githubusercontent.com/24428859/93373299-73630800-f855-11ea-859a-5803ea552700.png)
You can check it in runbot https://runbot.odoo-community.org/runbot/151/12.0

**Comment by emagdalenaC2i** [comment]
You should check https://github.com/OCA/account-invoicing/pull/704

**Comment by emagdalenaC2i** [comment]
Here you can see other example:
To replicate this issue:

1 - Set the **Round per line** option (Invoicing settings) and allow discounts (sale settings)

2- Create the next quotation
![image](https://user-images.githubusercontent.com/24428859/93576861-a4e5eb80-f99b-11ea-97fe-5ed696898d3d.png)

3 - Confirm the quotation and check the differences in the quotation, invoice and the Delivery Slip report
![image](https://user-images.githubusercontent.com/24428859/93576958-c3e47d80-f99b-11ea-94db-94fa8ef4b65d.png)

Here is the invoice
![image](https://user-images.githubusercontent.com/24428859/93577729-b380d280-f99c-11ea-9025-9ba00af57204.png)

So, this is not a Round globally issue.
