### ISSUE TITLE
Starting new translations on weblate

### ISSUE THREAD

**Issue by erik-bzcl** [OCA/stock-logistics-reporting#116]
Hello,

could you please kindly advise how to start new translations for OCA modules?

I have registered on weblate and sent an email to transbot as per instructions, also tried contacting directly through OCA website to get permission, but the button for starting a new translation on weblate remains disabled.

Should I create a PR with the added .po translation file? Is weblate used only for existing .po files?

**Comment by pedrobaeza** [comment]
You must wait until an answer is given to you saying you are in. cc @sbidoul

**Comment by sbidoul** [comment]
Hi @erik-bzcl , have you sent an email to transbot@odoo-community.org requested access to specific languages? I don't see any open request there.

**Comment by erik-bzcl** [comment]
@sbidoul yes I have on 13.09 but I have sent one again. Hope it doesn't go to spam.

Thanks!
