### ISSUE TITLE
[13.0] stock wrong when select child location in stock_quantity_history_location

### ISSUE THREAD

**Issue by chinmayivyas** [OCA/stock-logistics-reporting#176]
## Module
stock_quantity_history_location

## Describe the bug
The Inventory at date report is working for only parent locations, For the most child locations the report showing wrong qty for past date.
## To Reproduce
**Affected versions**: 13.0

1. Add stock in WH/stock/Shelf 1 for any stockable product [Ex Date:01/01/2022 ]
2. create a Delivery order on [Ex Date: 05/01/2022] and done that.
3.Now check inventory at Date report with WH/Stock location selected & WH/Stock/Shelf 1 selected with date: 01/01/2022

**Expected behavior**
On WH/Stock it will display correct qty for past date & for same date it will show wrong qty on Shelf 1 location, it should be display same qty for both the locations.

**Comment by paulius-sladkevicius** [comment]
Hello, I could confirm this issue too on the v14. In case you're using child locations to transfer product quantities then a report by location and date in past is not working correctly as Odoo is doing [calculations based](https://github.com/odoo/odoo/blob/77287edb77fb53836af2aa70c7b14c24e23d6002/addons/stock/models/product.py#L165-L166) on the `stock.move` but not a `stock.move.line`.

@HviorForgeFlow or @JordiBForgeFlow could you take a look? In case that won't be fixed, I suggest adding an extra remark in the description that it doesn't support cases when a final transfer is done to the child's location.
