### ISSUE TITLE
Stock Picking Report Valued and MRP Kit.

### ISSUE THREAD

**Issue by angelmoya** [OCA/stock-logistics-reporting#184]
If you have installed MRP and use a product with build of materials as kit, when you sale it, the pickig report valued get wrong data, get the product of components quantityt by proudct price.

![S00023 - Odoo](https://user-images.githubusercontent.com/6750341/157649044-ce1e414d-72b4-4a17-83ea-a8937a4db096.png)

![Delivery Slip - Deco Addict - WH_OUT_00013 (2) pdf](https://user-images.githubusercontent.com/6750341/157649079-13ef816f-26ec-4d9e-92cd-8facaad60789.png)

## Module
- stock_picking_report_valued
- mrp

## To Reproduce
All versions:

Sell demo product FURN_78236, confirm sale order, confirm delivery and print delivery slip.

**Comment by pedrobaeza** [comment]
https://github.com/OCA/stock-logistics-reporting/tree/13.0/stock_picking_report_valued_sale_mrp

**Comment by angelmoya** [comment]
Thanks @pedrobaeza  and sorry for the noise
