### ISSUE TITLE
Stock reporting by location at date

### ISSUE THREAD

**Issue by rousseldenis** [OCA/stock-logistics-reporting#188]
I looked for a module implementing stock reporting grouped by location at date.

I think this one fits nearly my needs : https://github.com/OCA/stock-logistics-reporting/tree/12.0/stock_report_quantity_by_location

@AaronHForgeFlow Do you think it could be a good feature to add date in the product context in order to obtain the good result ?

I think I will do it and migrate yours to 14.

**Comment by AaronHForgeFlow** [comment]
Hi @rousseldenis , yes I think this would be a nice improvement. There is an open PR to version 14.0: https://github.com/OCA/stock-logistics-reporting/pull/173 

Perhaps you can review that one and then we can merge this and you can propose an improvement.

**Comment by rousseldenis** [comment]
> Hi @rousseldenis , yes I think this would be a nice improvement. There is an open PR to version 14.0: #173
> 
> Perhaps you can review that one and then we can merge this and you can propose an improvement.

I've tested it and it's not possible as the quantity query is done through read_group.

**Comment by AaronHForgeFlow** [comment]
Yes,  I think that was done for performance issues. So probably another different report will be needed that covers your use case.
