### ISSUE TITLE
[13] stock_picking_report_valued_sale_mrp ERROR on installing

### ISSUE THREAD

**Issue by sergioeix** [OCA/stock-logistics-reporting#190]
## Module
stock_picking_report_valued_sale_mrp 

## Describe the bug
When you try to install the module an error is displayed

odoo.tools.convert.ParseError: "Element 'xpath expr="//tr[@t-foreach='o.move_line_ids']" cannot be located in parent view

Error context:
View `valued_report_picking`
[view_id: 1206, xml_id: n/a, model: n/a, parent_id: 1204]" while parsing /mnt/data/odoo-addons-dir/stock_picking_report_valued_sale_mrp/report/stock_picking_report_valued.xml:2, near

![image](https://user-images.githubusercontent.com/62206774/163210525-7444e2a7-2845-4236-96ec-9ba71199aaaa.png)

## To Reproduce
**Affected versions**: 13

1. try to install
2. 
3.
You can check it on runbot, just unistall it and try to install it again

**Expected behavior**
Install without issues

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
You have somehow your report changed in the DB you are installing the module, but it's not a problem of it.

**Comment by sergioeix** [comment]
@pedrobaeza I think its not only on my db because you can do this on runbot, just uninstall stock_picking_report_valued_sale_mrp and try to install it again

**Comment by pedrobaeza** [comment]
OK, let me check.
