### ISSUE TITLE
[15] stock_picking_report_valued: wrong data on stock picking report

### ISSUE THREAD

**Issue by bi-landoo** [OCA/stock-logistics-reporting#225]
@chienandalu @carlosdauden @pedrobaeza @ao-landoo @flachica

I have been testing stock_picking_report_valued and data shown on stock picking report is not correct.

I attach a few pictures to describe the problem detected on runboat.

1. There is a missing label for last field on stock picking
2. Order of fields is wrong.

![Pedido-S00027-1-pdf](https://user-images.githubusercontent.com/105443633/189615698-e89a44a7-f735-4347-9f80-ca87cfbd4393.png)

![Albarán-de-entrega-Cliente-Prueba-WH_OUT_00016-1-pdf](https://user-images.githubusercontent.com/105443633/189615730-c3d4ccde-c608-4227-9d5c-362b53b69c2c.png)

**Comment by pedrobaeza** [comment]
We haven't migrated this module to 15.0. You should query @flachica as well.

**Comment by flachica** [comment]
I'm trying to fix this in #226 

On my instance this error does not appear. I guess it's because I don't have the same modules installed.

How could I test the module in runboat?

**Comment by flagreenice** [comment]
@bi-landoo Fix was merged yesterday
