### ISSUE TITLE
[15.0] stock_picking_report_valued: Fields displayed on picking report with wrong label

### ISSUE THREAD

**Issue by bi-landoo** [OCA/stock-logistics-reporting#234]
When activating the followin setting on Inventory app:

- Display Lots & Serial Numbers on Delivery Slips (group_lot_on_delivery_slip)

Picking report's table's values are not placed correctly.

I'm adding an image of a report without this setting, and after another with the setting activated.
![image](https://user-images.githubusercontent.com/105443633/194319779-598311c1-ff71-4622-b6fe-6e21a2a31df2.png)
![image](https://user-images.githubusercontent.com/105443633/194320065-587c4c3c-1be8-4ae6-ab95-198617124952.png)

@flagreenice @flachica @ernestotejeda @sergio-teruel @pedrobaeza @ao-landoo

**Comment by sergio-teruel** [comment]
@bi-landoo fixed!! please review

**Comment by bi-landoo** [comment]
@sergio-teruel order of displayed fields is correct! Thanks

But be careful, you forgot to delete "ppp" (please see picture below)

![image](https://user-images.githubusercontent.com/105443633/194498374-6632e887-4df5-4fa0-ad3e-19a79b9ab23c.png)

**Comment by sergio-teruel** [comment]
Fixed!!! thanks
