### ISSUE TITLE
[15] stock_picking_client_note (or maybe stock_picking_external_note)

### ISSUE THREAD

**Issue by rafaelbn** [OCA/stock-logistics-reporting#264]
We need to add a text field `note` in stock picking to be printed in delivery slip. The development is really simple.

- [x] Create a new field client_note (html) in the same way note is created in core
- [x] Print this new field in client delivery slip

I know already all the alternatives and no one is the requirement.

- ~~https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_picking_comment_template~~ when you have templates or comments. In this use case every comment is different in each picking
- ~~https://github.com/OCA/stock-logistics-reporting/tree/14.0/stock_picking_report_custom_description~~ bring the description of sales to picking
- ~~https://github.com/OCA/stock-logistics-workflow/tree/14.0/stock_delivery_note~~ depends on delivery module

Odoo has a field note for internal comments for each picking which are only printed in picking operations

We need a external one to be printed only in delivery slip and not from sale order or any other related document

We will make a PR soon.

@moduon MT-2153

Regards

**Comment by Shide** [comment]
How about https://github.com/OCA/stock-logistics-workflow/tree/14.0/stock_delivery_note ?

I only need to migrate to v15 and change the type of the field from Text to Html

**Comment by Shide** [comment]
I'm creating a new module because previous suggestion depends on delivery module: https://github.com/OCA/stock-logistics-reporting/pull/269

**Comment by rafaelbn** [comment]
https://github.com/OCA/stock-logistics-reporting/pull/269
