### ISSUE TITLE
Print customer address in all pages of a stock.picking report (delivery slip)

### ISSUE THREAD

**Issue by rafaelbn** [OCA/stock-logistics-reporting#33]
Hello!

Anyone have solve the issue of printing the "Customer Address" in all the pages of a Delivery slip?

If you send big deliveries with many lines and the report has 5 o 20 pages you can check in the footer the pages 1/2 .... 5/20 but the name of Customer is only in the **first page**.

We see limitations with wkhtmltopdf.

Any idea?

Thanks!
Regards

**Comment by hbrunn** [comment]
I think you could do this with https://github.com/OCA/reporting-engine/tree/9.0/report_qweb_pdf_watermark - use the expression variant, and then write some code that generates a pdf with the customer address on the right place. This can probably be generated from a second report, this way you stay clean and modular.

**Comment by smangukiya** [comment]
You should work on default header layout in report. And use that custom header layout(supporting customer address part) to delivery report.

Thanks

**Comment by OSevangelist** [comment]
Hi together, 
one of my developers suggested custom headers / footers to solve the issue 
see

https://www.odoo.com/de_DE/forum/hilfe-1/question/how-to-have-custom-header-in-qweb-report-68544
https://odootricks.wordpress.com/2014/11/05/how-to-change-the-default-headerfooter-in-odoo-8-pdf-reports-salequoteinvoice/

maybe that is an alternative for you

**Comment by hbrunn** [comment]
I suggested the background because headers tend to eat up a lot of space, and cannot overlap with the main content area. but if you don't mind the space, the header is indeed the way to go

**Comment by OSevangelist** [comment]
@hbrunn i don't like the layered approach that much because of programming clarity but that's more feelings than real facts

My developer also suggested:

`<t t-foreach="docs" t-as="o">
    <div class="header">
        <p>Kunde: <span t-field="o.partner_id.name"/></p>
    </div>
    <div class="page">
        ....
    </div>
    <div class="footer">
        ....
    </div>
</t>
`
In order to solve the whole problem of @rafaelbn

**Comment by rafaelbn** [comment]
Hi, thanks! @sergio-teruel found how yo solve this. Maybe he can explain it here. @Tecnativa

**Comment by pedrobaeza** [comment]
The trick finally has been including the content to repeat in the header of a multi-page table. Thanks all for answering.
