### ISSUE TITLE
This repo cannot be published in Odoo App Store (branch 10.0)

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/stock-logistics-reporting#43]
See below the error listed in odoo's page for registered repositories:

![image](https://user-images.githubusercontent.com/7683926/37134662-cc29ce7c-2299-11e8-940c-92f6a79cd3e7.png)

**Comment by JordiBForgeFlow** [comment]
cc @OCA/board

**Comment by pedrobaeza** [comment]
Uhm, this is the problem with modules started in other branch. This time is one of mine, but I don't know the procedure to grant permission to move it.
