### ISSUE TITLE
Print barcode of the next picking

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-reporting#47]
# Context

* 3-steps delivery process
* the pickers don't use Odoo and don't have mobile barcode scanners
* the packers use Odoo and have USB barcode scanners

# Process

* The picker manager prints the picking wave/picking reports and hand it over to the pickers.
* The pickers run across the warehouse with their cart and pick items
* The picker leaves his cart with the picked items and the sheet of paper to the picker manager.
* The picker manager reviews/checks the content and validates the picking in Odoo
* The picker manager pushes the cart to one of the packing station

# Problem

* The packer has no quick and easy way (= scan something) to open the corresponding packing order.

# Proposed solution

* The barcode of the packing order is added on the "Picking Operations" report of the picking order.
* The packer scans the barcode to open the packing order

**Comment by rousseldenis** [comment]
@max3903 Could you close this ? Do you plan to port it to OCA?
