### ISSUE TITLE
Stock Card / Bin Card - Report in PDF and Excel

### ISSUE THREAD

**Issue by kittiu** [OCA/stock-logistics-reporting#64]
Hi, we are looking into developing the stock_card_report in pdf and excel, which should be similar to this one,

https://apps.odoo.com/apps/modules/12.0/hyd_stock_card/

Search criteria:
- Start date
- End date
- Products
- Warehouse / Location

The result should show product one by one, with result -> Initial Balance, In, Out, End Balance

May I check whether some work has been developed in OCA, and/or should I develop it (i.e., stock_card_report)

@ps-tubtim

**Comment by kittiu** [comment]
@rousseldenis should I do this, WDYT?

**Comment by rousseldenis** [comment]
@kittiu I've no requirement for that at the moment, but if you have, go on!

**Comment by kittiu** [comment]
@rousseldenis thanks

**Comment by kittiu** [comment]
@rousseldenis I am a quite confused about stock.move, stock.move.line and stock.quant
What are the difference?
With the given requirement, which table in your opinion best represent the detailed moves.

**Comment by rousseldenis** [comment]
@kittiu The model to represent real done movements is stock.move.

The stock.move.line is the detailed operations done by user (if multiple sub-locations movements for a same product).

The stock.quant represent the current stock quantity for a given product, lot, owner and incoming date.

**Comment by kittiu** [comment]
Thank you @rousseldenis I am much clearer now. We will start doing this report.
So, I would think stock.move is suitable for this report. @ps-tubtim

**Comment by ps-tubtim** [comment]
@All Please review at https://github.com/OCA/stock-logistics-reporting/pull/69 . Thank you.
