### ISSUE TITLE
Stock Valuation Report in PDF / Excel

### ISSUE THREAD

**Issue by kittiu** [OCA/stock-logistics-reporting#71]
Hello,
We would like to imitate the current stock valuation report in Odoo to also print PDF (qweb) and Excel report (report_xlsx).
Just a normal check here whether it will be ok here, and not already been developed.
Thank you.

Note: we plan to make it new addon, i.e., stock_inventory_valuation_report

![image](https://user-images.githubusercontent.com/1973598/63219458-a6dbea80-c19c-11e9-908b-d71f7805bec9.png)

**Comment by rafaelbn** [comment]
This would be great! Thanks 👍

**Comment by pedrobaeza** [comment]
Yes, there's still nothing about this. Very welcome!

**Comment by kittiu** [comment]
Thank you both. @ps-tubtim, let's do it!

**Comment by rafaelbn** [comment]
PSC can close this issue has PR is opened https://github.com/OCA/stock-logistics-reporting/pull/72
