### ISSUE TITLE
travis.yml outdated for 8.0 branch

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/stock-logistics-reporting#8]
Need to be updated for getting green.

**Comment by eLBati** [comment]
Fixing with https://github.com/OCA/stock-logistics-reporting/pull/10

**Comment by eLBati** [comment]
This can be closed

**Comment by pedrobaeza** [comment]
Well, not exactly, because README still points to master branch, but I have changed it through direct commit to fast track it, and now it can be closed
