### ISSUE TITLE
[12.0][BUG][stock_inventory_valuation_report] Incorrect valuation with multi-currency

### ISSUE THREAD

**Issue by rafaelbn** [OCA/stock-logistics-reporting#88]
Hi @ps-tubtim @kittiu ,

To reproduce:

- Your company works in Dollars
- You make a purchase in CNY
- Report should be in Dollars, this module show report mixing Dollars and CNY

Do you think you could fix it?

Thanks
Regards

**Comment by ps-tubtim** [comment]
@rafaelbn I don't found this bug in runbot. Could you show your bug to me?

![2020-01-15_09-46](https://user-images.githubusercontent.com/51266019/72400713-b4fa5b00-377c-11ea-88cd-8987192b916f.png)

![2020-01-15_09-47](https://user-images.githubusercontent.com/51266019/72400720-b9267880-377c-11ea-8074-9c649e92eccb.png)

![2020-01-15_09-48](https://user-images.githubusercontent.com/51266019/72400731-bcb9ff80-377c-11ea-8172-77aadf89ea38.png)

![2020-01-15_09-49](https://user-images.githubusercontent.com/51266019/72400741-c0e61d00-377c-11ea-9082-b5a7f926c3d5.png)

![2020-01-15_09-50](https://user-images.githubusercontent.com/51266019/72400746-c479a400-377c-11ea-9573-03ec0b4dabb1.png)

**Comment by rafaelbn** [comment]
Hi @ps-tubtim ,

We always use "Costing Method | Average Cost (AVCO)"

- http://3403249-12-0-02aba4.runbot3.odoo-community.org/web?debug=1#id=11&action=345&model=purchase.order&view_type=form&menu_id=204

- https://www.tecnativa.com/web#model=project.task&view_type=form&id=21341&active_id=21341&menu_id=

Take a look at this video I've recorded in runbot

https://drive.google.com/file/d/1tj_yLChOPR1AdQ7MxVZK4ZkskhXekU0L/view?usp=sharing

Thanks
Regards
