### ISSUE TITLE
Inventory Valuation by Location 

### ISSUE THREAD

**Issue by Tempronics1** [OCA/stock-logistics-reporting#94]
module: stock_quantity_history_location
version: 12.0

**Steps to reproduce**
- ...Under Inventory Valuation, I'm not seeing the "Location" field. It only appears under Inventory  Report. I was under the impression that it should appear under both. Is there something I'm missing. Thanks. 

**Current behavior**

**Expected behavior**

**Comment by HviorForgeFlow** [comment]
It is not possible to have an accurate Inventory Valuation by location. stock_account_quantity_history_location module is auto-installable when you have Stock Accounting installed and warns you that filter by location is not calculated properly.
![image](https://user-images.githubusercontent.com/32061121/75752874-d8c43100-5d29-11ea-9efd-c8df51d1fb13.png)
