### ISSUE TITLE
[12.0][BUG][stock_inventory_valuation_report]

### ISSUE THREAD

**Issue by microsound1** [OCA/stock-logistics-reporting#96]
Hi all,

I am using FIFO with automatic valuation, when I do a "Reporting" --> "Inventory valuation" choosing a specific date and click on "Export XLSX" some product missing from the report. As I see those products missing which currently at Today's date has quantity 0, however at the chosen specific date it had available quantity either 1 or more.

If using the standard button "Retreive the inventory valuation" using the same specific date as earlier, it shows correctly. Displays those products which missing from the excel report.

**Comment by SimoRubi** [comment]
@microsound1 thanks for reporting this, could you please check if https://github.com/OCA/stock-logistics-reporting/pull/140 fixes the issue?

**Comment by microsound1** [comment]
@SimoRubi it is now displays product quantity correctly, however with 0 value. I am not sure it has to do something on my side, because everytime I need a past inventory report, I need to uninstall "stock_account_valuation_report" otherwise I get an empty report in excel with the header only.

**Comment by SimoRubi** [comment]
@microsound1 the reports created by the module `stock_inventory_valuation_report` only show products that were available at the selected date, that comes from: https://github.com/OCA/stock-logistics-reporting/blob/3e97398e14be52501fd93120a722476d54e93fe1/stock_inventory_valuation_report/reports/stock_inventory_valuation_report.py#L75-L76
Maybe there are no products available at the date you selected?
That would explain the report showing only the header.
